language: java
jdk: oraclejdk8
env:
  global:
  - secure: TQZGDK1eLnY/PFC41ESFRob0dfmhIehuY9n3OVu3gUKrLjEZS5VqTWczx54jrtB0bHH46ZogthATjpaJwgOoAI2AuqHiz3reCAgKA4XE/gGhgiIDLUTUg+fbG6frEPRjWB/OBamCWIip3pB6Acm/nqczFCAVfK2OIyQZvyCGFO0=
addons:
  coverity_scan:
    project:
      name: stevespringett/dependency-track
      description: Dependency-Track Coverity Scan
    notification_email: Steve.Springett@owasp.org
    build_command_prepend: 
    build_command: mvn clean package
    branch_pattern: coverity_scan

before_script:
  - export REPO=owasp/dependency-track
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "snapshot"; else echo $TRAVIS_BRANCH ; fi`

script:
  - mvn clean package
  - mvn package -P embedded-jetty -Dlogback.configuration.file=src/main/docker/logback.xml
  - docker build -f src/main/docker/Dockerfile -t $REPO:$TAG .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push $REPO;
    fi

notifications:
  slack:
    secure: FtU/UJX7A904c3JgrQ9AE5zYWO8gIMhzAfL8MFRbUd2AfFbNNpb1OaEbIr61Ho0V/HpBYiL/4YDaINKhy/VeUyz1hqAQingvwip6XrblpoEV2bGXZNVOLW72/z41qNwZ2q7Ebx3F1L1jHSUUPBs91FaqWWpwVNXi5FWPT7OkGv0=
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ade5cc3a87ec0ea4d2c8
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always